"""Gave a range to string in resolution_status

Revision ID: 73269d75e434
Revises: acaa8d6c7f70
Create Date: 2023-09-02 11:43:39.598950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73269d75e434'
down_revision: Union[str, None] = 'acaa8d6c7f70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
