"""Linked with Foreign Key

Revision ID: acaa8d6c7f70
Revises: 5097bd6ce16c
Create Date: 2023-09-01 23:30:47.569548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acaa8d6c7f70'
down_revision: Union[str, None] = '5097bd6ce16c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
