"""Remmoved two columns

Revision ID: b0d1d372b406
Revises: 2e33acff8cff
Create Date: 2023-09-01 23:28:12.103839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0d1d372b406'
down_revision: Union[str, None] = '2e33acff8cff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('claimed_by')
        batch_op.drop_column('found_by')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('found_by', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('claimed_by', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
