"""Removed unique key

Revision ID: e78a1ee5a884
Revises: feef8cee92ac
Create Date: 2023-08-30 15:55:02.727684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e78a1ee5a884'
down_revision: Union[str, None] = 'feef8cee92ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=55), nullable=False))
        batch_op.drop_column('contact')
        batch_op.drop_column('lastname')
        batch_op.drop_column('firstname')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstname', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('lastname', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('contact', sa.TEXT(), nullable=False))
        batch_op.drop_column('email')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
